export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as Navbar} from './admin/navbar/Navbar'
export {default as Home } from './admin/home/Home'
export {default as ViewProducts} from './admin/viewProducts/ViewProducts'
export { default as AddProduct} from './admin/addProducts/AddProduct'
export {default as Orders} from './admin/orders/Oders'